<img src="https://raw.githubusercontent.com/paular143/images_notebooks/master/logo-sin-nombre.png" alt="Universidad de Los Andes" style="width: 90px;" align="left" frameborder="300"/>

**UNIVERSIDAD DE LOS ANDES** <br>
**FACULTAD DE ECONOMÍA** <br>
**TÓPICOS EN APRENDIZAJE DE MÁQUINAS** <br>
**PROFESOR COMPLEMENTARIO:** Nicolás Rugeles <br><br>

__Objetivo__: Introdución a la implementación e interpretación de modelos lineales y árboles de clasificación.

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error

In [2]:
dataset= datasets.load_diabetes()

In [3]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [4]:
dataset['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [5]:
dataset.get('data')

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
datos=pd.DataFrame(dataset.get('data'),columns=dataset['feature_names'])

In [7]:
datos

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [8]:
datos['pert']= 2*(np.random.random(size=datos.shape[0])-0.5)/5

In [9]:
datos['target']= 3*datos['age']+2*datos['bmi']+4*datos['s1']+datos['pert']

In [10]:
X=datos.iloc[:,:-2]
Y=datos.iloc[:,-1]

In [11]:
x_train=X.iloc[:-20]
x_test = X.iloc[-20:]
y_train= Y[:-20]
y_test= Y[-20:]

In [12]:
regr = linear_model.LinearRegression()

In [13]:
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

In [14]:
# The coefficients
print("Coefficients: \n", pd.DataFrame(regr.coef_,dataset['feature_names']))
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Coefficients:
             0
age  2.942972
sex  0.100739
bmi  2.063472
bp  -0.023611
s1   3.630077
s2   0.277115
s3   0.253691
s4   0.308085
s5   0.023314
s6   0.246023
Mean squared error: 0.02

In [15]:
lasso = linear_model.Lasso(alpha=0.00000001)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
# The coefficients
print("Coefficients: \n", pd.DataFrame(lasso.coef_,dataset['feature_names']))
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Coefficients:
             0
age  2.942970
sex  0.100732
bmi  2.063467
bp  -0.023601
s1   3.630299
s2   0.276951
s3   0.253564
s4   0.308028
s5   0.023233
s6   0.246021
Mean squared error: 0.02

# Datos arboles

In [18]:
from sklearn.datasets import load_iris

In [19]:
data = load_iris()
data_iris = pd.DataFrame(data.data, columns=data.feature_names)
data_iris['target'] = data.target
data_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [20]:
data_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [21]:
data_iris.columns= ['sepal_l','sepal_w','petal_l','petal_w','target']

In [22]:
X = data_iris.data
type(X)
print(X[0:5,:])
X.shape

AttributeError: 'DataFrame' object has no attribute 'data'

In [23]:
print(X[-5:,:])

InvalidIndexError: (slice(-5, None, None), slice(None, None, None))

In [36]:
# Analizamos los tipos de las variables
data_iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n|details-start|\n**References**\n|details-split|\n\n- Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n  Mathematical Statistics" (John Wiley, NY, 1950).\n- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n  Structure and Classification Rule for Recognition in Partially Exposed\n  Environments".  IEEE Transactions on Pattern Analysis and Machine\n  Intelligence, Vol. PAMI-2, No. 1, 67-71.\n- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n  on Information Theory, May 1972, 431-433.\n- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n  conceptual clustering system finds 3 classes in the data.\n- Many, many more ...\n\n|details-end|\n'

## Muestra de entrenamiento y evaluación.

In [37]:
from sklearn.model_selection import train_test_split # Para partir la base de datos en train y test

In [38]:
x_train, x_test, y_train, y_test = train_test_split(data_iris.drop(columns=["target"]), data_iris.target, test_size=0.3, 
    random_state=123, stratify=data_iris.target)

AttributeError: drop

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

In [ ]:
x=np.random.random(1000)
x.sort()

## Evaluación de modelo

In [ ]:
from sklearn import metrics

In [ ]:
y_hat = clf.predict(x_test)
y_hat_train = clf.predict(x_train)

In [ ]:
metrics.confusion_matrix(y_test,y_hat)

In [ ]:
metrics.accuracy_score(y_test,y_hat)

In [ ]:
metrics.confusion_matrix(y_train,y_hat_train)

In [ ]:
y_test.unique()

In [ ]:
# Plotear
import matplotlib.pyplot as plt
from sklearn import tree
plt.figure(figsize=(20, 20))

tree.plot_tree(clf, feature_names=list(x_train.columns), 
               filled=True, label="none", proportion=True, class_names=['versicolor', 'virginica', 'setosa']);

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
## Corss-Validation

search_space_rf = [{
    'max_depth': [1,2, 3, 4, 5],
    'splitter': ['best', 'random'] 
}]

clf = GridSearchCV(DecisionTreeClassifier(random_state=123), search_space_rf, scoring="accuracy", cv=5
                   , verbose=4,return_train_score=True)
clf.fit(x_train, y_train);

In [ ]:
pd.DataFrame(clf.cv_results_)

In [ ]:
from sklearn import datasets

In [ ]:
# Generate synthetic dataset
X, y = datasets.make_classification(
    n_samples=1000,  # Total number of samples
    n_features=5,    # Number of features
    n_classes=1,     # Number of classes (binary classification)
    random_state=42, # Random seed for reproducibility
)